Select project subset

In [16]:
import pandas as pd
df = pd.read_csv("Reproducibility_Data.csv")
df

,project_name,primary_language,window_starts,window_ends,Events,NLOC,LevD,Tokens,CycC,Functions,...,HalEff,TS,N,E,Diam,Dens,ClustC,InD,EigG,FModR
0,7compass__sentimental__2020-06-13_10-18-00,Ruby,1.438313e+09,1.463714e+09,81.500000,42.166667,1.863167e+03,255.000,7.166667,6.166667,...,6.940068e+04,6,7,97.0,4.0,0.166667,0.238095,1.000000,0.059379,0.261646
1,7compass__sentimental__2020-06-13_10-18-00,Ruby,1.463714e+09,1.489116e+09,1.500000,0.500000,2.950000e+01,4.000,0.000000,0.000000,...,7.148010e+02,2,4,3.0,1.0,0.166667,0.000000,0.500000,0.000002,1.000000
2,airbnb__enzyme__2020-06-11_01-31-34,JavaScript,1.459010e+09,1.484411e+09,79.850000,56.275000,2.066575e+03,340.625,11.125000,8.625000,...,6.308872e+05,40,55,222.0,4.0,0.020202,0.189339,1.090909,0.153405,0.178870
3,airbnb__enzyme__2020-06-11_01-31-34,JavaScript,1.484411e+09,1.509813e+09,110.750000,65.900000,3.160900e+03,394.175,14.225000,7.775000,...,1.050828e+05,40,64,840.0,5.0,0.023065,0.258783,1.453125,0.172376,0.307815
4,airbnb__enzyme__2020-06-11_01-31-34,JavaScript,1.509813e+09,1.535215e+09,61.150000,33.050000,1.721125e+03,193.600,8.525000,3.050000,...,7.388522e+04,40,54,616.0,4.0,0.028651,0.206420,1.518519,0.061510,0.418407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,xiaofengli__codebank__2020-06-14_04-38-01,NaN,1.541009e+09,1.566411e+09,1840.000000,1339.000000,4.739400e+04,8448.000,151.333333,75.000000,...,3.966254e+05,3,3,68.0,1.0,0.333333,0.000000,0.666667,0.000002,0.029304
1423,zclconf__go-cty__2020-06-13_23-30-00,Go,1.532944e+09,1.558345e+09,478.400000,357.800000,1.200420e+04,2241.400,37.800000,7.200000,...,9.498268e+05,5,5,28.0,2.0,0.250000,0.000000,1.000000,0.000002,0.130496
1424,zclconf__go-cty__2020-06-13_23-30-00,Go,1.558345e+09,1.583747e+09,506.600000,400.000000,1.252300e+04,2606.000,37.400000,8.800000,...,1.714379e+06,5,6,33.0,2.0,0.133333,0.000000,0.666667,0.000002,0.029320
1425,zs6buj__MavlinkToPassthru__2020-06-13_00-21-03,C,1.540464e+09,1.565866e+09,102320.500000,70065.500000,3.715830e+06,486462.500,16417.000000,2548.500000,...,8.714068e+08,2,2,27.0,1.0,1.000000,NaN,1.000000,0.000002,0.132984
1426,zs6buj__MavlinkToPassthru__2020-06-13_00-21-03,C,1.565866e+09,1.591267e+09,548454.333333,351597.333333,2.360942e+07,2885870.000,61097.333333,23176.000000,...,5.198504e+09,3,3,4.0,1.0,0.333333,0.000000,0.666667,0.000002,0.143590

In [17]:
# Keep only the latest time interval.
df = df.loc[df.groupby("project_name")["window_ends"].idxmax()]
df

,project_name,primary_language,window_starts,window_ends,Events,NLOC,LevD,Tokens,CycC,Functions,...,HalEff,TS,N,E,Diam,Dens,ClustC,InD,EigG,FModR
1,7compass__sentimental__2020-06-13_10-18-00,Ruby,1.463714e+09,1.489116e+09,1.500000,0.500000,2.950000e+01,4.000000e+00,0.000000,0.000000,...,7.148010e+02,2,4,3.0,1.0,0.166667,0.000000,0.500000,0.000002,1.000000
92,Automattic__jetpack__2020-06-11_01-31-57,PHP,1.555420e+09,1.580821e+09,420.263158,167.403509,1.185408e+04,9.261228e+02,33.482456,19.824561,...,1.483046e+06,114,201,8035.0,6.0,0.017040,0.323264,3.407960,0.104432,0.229114
103,Azure__azure-sdk-for-node__2020-06-13_10-23-37,JavaScript,1.543898e+09,1.569300e+09,15149.727273,5339.000000,5.111286e+05,3.231091e+04,1376.727273,273.363636,...,5.862298e+07,11,38,15702.0,4.0,0.032717,0.129369,1.210526,0.071246,0.260059
108,Azure__sonic-buildimage__2020-06-14_00-16-59,C,1.564242e+09,1.589644e+09,1337.142857,881.414286,4.148610e+04,5.425271e+03,161.528571,44.228571,...,9.727807e+06,70,90,3412.0,10.0,0.019725,0.295254,1.755556,0.004270,0.128800
154,CopterExpress__clever__2020-06-13_00-30-49,C++,1.566441e+09,1.591842e+09,321.500000,183.000000,9.654750e+03,1.526500e+03,33.750000,7.000000,...,1.088229e+06,4,7,156.0,3.0,0.214286,0.204762,1.285714,0.138262,0.119686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1401,xfce-mirror__xfce4-timer-plugin__2020-06-13_00...,C,1.513914e+09,1.539315e+09,52.666667,12.333333,1.290667e+03,1.363333e+02,1.000000,0.666667,...,6.443301e+05,3,4,27.0,1.0,0.416667,0.833333,1.250000,0.125023,0.156537
1421,xfce-mirror__xfdesktop__2020-06-13_00-05-56,C,1.560706e+09,1.586107e+09,54.833333,33.000000,1.949000e+03,1.800000e+02,8.000000,0.833333,...,1.854802e+06,6,14,53.0,1.0,0.060440,0.000000,0.785714,0.000002,0.315772
1422,xiaofengli__codebank__2020-06-14_04-38-01,NaN,1.541009e+09,1.566411e+09,1840.000000,1339.000000,4.739400e+04,8.448000e+03,151.333333,75.000000,...,3.966254e+05,3,3,68.0,1.0,0.333333,0.000000,0.666667,0.000002,0.029304
1424,zclconf__go-cty__2020-06-13_23-30-00,Go,1.558345e+09,1.583747e+09,506.600000,400.000000,1.252300e+04,2.606000e+03,37.400000,8.800000,...,1.714379e+06,5,6,33.0,2.0,0.133333,0.000000,0.666667,0.000002,0.029320
1426,zs6buj__MavlinkToPassthru__2020-06-13_00-21-03,C,1.565866e+09,1.591267e+09,548454.333333,351597.333333,2.360942e+07,2.885870e+06,61097.333333,23176.000000,...,5.198504e+09,3,3,4.0,1.0,0.333333,0.000000,0.666667,0.000002,0.143590

In [24]:
# Sort by team size.
df_sub = df[["project_name", "primary_language", "TS"]].sort_values("TS", ascending=False)

In [25]:
# Filter projects with primary language supported by Kaiaulu.
supported = ["Java", "C", "C++"]
# TODO

In [26]:
# Filter projects with team size 872-1711
df_sub.loc[df_sub["TS"] >= 872]

                                     project_name primary_language    TS
498  Homebrew__homebrew-core__2020-06-11_15-11-44             Ruby  1086

In [28]:
# Filter projects with team size 444-871
df_sub.loc[(df_sub["TS"] >= 444) & (df_sub["TS"] < 872)]

                                           project_name primary_language   TS
1315        tensorflow__tensorflow__2020-06-13_06-54-28              C++  648
476   home-assistant__home-assistant__2020-06-13_12-...           Python  616
26                ansible__ansible__2020-06-11_06-06-22           Python  576
633         kubernetes__kubernetes__2020-06-12_04-18-31               Go  570
1144               rust-lang__rust__2020-06-14_10-03-01             Rust  564
323               gatsbyjs__gatsby__2020-06-10_13-07-25       JavaScript  522
830        nodejs__node-chakracore__2020-06-13_15-27-44       JavaScript  459

In [31]:
# Filter projects with team size 227-443
df_sub.loc[(df_sub["TS"] >= 227) & (df_sub["TS"] < 444)]

                                         project_name primary_language   TS
690          magento__graphql-ce__2020-06-14_03-59-24              PHP  394
759         mui-org__material-ui__2020-06-13_17-40-59       JavaScript  390
647           laravel__framework__2020-06-14_05-21-26              PHP  387
898           pandas-dev__pandas__2020-06-10_23-21-53           Python  364
1008             python__cpython__2020-06-11_06-27-42           Python  362
697            magento__magento2__2020-06-14_00-37-06              PHP  342
1045           qmk__qmk_firmware__2020-06-11_05-23-27                C  321
884       oprietop__qmk_firmware__2020-06-11_06-25-00                C  321
1160  scikit-learn__scikit-learn__2020-06-11_01-38-33           Python  312
1036                  qemu__qemu__2020-06-12_23-19-38                C  308
409           godotengine__godot__2020-06-13_23-35-41              C++  298
425                   golang__go__2020-06-13_22-24-40               Go  294
32               apache__airflow__2020-06-13_20-27-45           Python  275
1083                rails__rails__2020-06-13_10-52-43             Ruby  260
929            prebid__Prebid.js__2020-06-14_00-22-44       JavaScript  230

In [32]:
# Filter projects with team size 116-226
df_sub.loc[(df_sub["TS"] >= 116) & (df_sub["TS"] < 227)]

                                       project_name primary_language   TS
43               apache__flink__2020-06-11_13-39-22             Java  220
277     facebook__react-native__2020-06-13_22-58-43       JavaScript  219
1319     TheAlgorithms__Python__2020-06-13_10-17-19           Python  194
361         gitlabhq__gitlabhq__2020-06-11_10-44-27             Ruby  191
1058                qt__qtbase__2020-06-13_17-39-48              C++  160
752           mrdoob__three.js__2020-06-10_11-31-04       JavaScript  147
1398  woocommerce__woocommerce__2020-06-13_10-35-05              PHP  143
1105   reactjs__es.reactjs.org__2020-06-13_12-14-58       JavaScript  142
67              apache__hadoop__2020-06-10_23-15-51             Java  141
292     flow-typed__flow-typed__2020-06-14_03-58-42       JavaScript  129

In [33]:
# Filter projects with team size 59-115
df_sub.loc[(df_sub["TS"] >= 59) & (df_sub["TS"] < 116)]

                                           project_name primary_language   TS
92             Automattic__jetpack__2020-06-11_01-31-57              PHP  114
441                     grpc__grpc__2020-06-13_01-25-27              C++  111
271     facebook__create-react-app__2020-06-13_06-53-12       JavaScript   93
185                     dask__dask__2020-06-11_06-23-16           Python   92
256          ethereum__go-ethereum__2020-06-13_23-33-01               Go   89
952                     PX4__NuttX__2020-06-12_19-32-40                C   87
1263  spring-projects__spring-framework__2020-06-13_...             Java   84
74                  apache__ignite__2020-06-13_00-06-19             Java   79
973             pytest-dev__pytest__2020-06-14_09-39-01           Python   78
601              keras-team__keras__2020-06-10_11-30-11           Python   76
638   kubernetes-sigs__cluster-api__2020-06-10_23-14-50               Go   75
861              openshift__origin__2020-06-12_19-40-32               Go   73
337              getsentry__sentry__2020-06-13_15-35-39           Python   73
108        Azure__sonic-buildimage__2020-06-14_00-16-59                C   70
396                     GNOME__gtk__2020-06-13_12-30-17                C   70
368       gitlabhq__omnibus-gitlab__2020-06-11_13-32-12             Ruby   64
159             cosmos__cosmos-sdk__2020-06-13_10-33-05               Go   64
463                   helm__charts__2020-06-11_01-48-27               Go   64

In [34]:
# Filter projects with team size 31-54
df_sub.loc[(df_sub["TS"] >= 31) & (df_sub["TS"] < 60)]

                                           project_name primary_language  TS
538         jellyfin__jellyfin-web__2020-06-14_05-03-08       JavaScript  58
663                 lutris__lutris__2020-06-13_12-28-18           Python  56
1244            sphinx-doc__sphinx__2020-06-13_10-43-06           Python  53
924          prebid__prebid-server__2020-06-11_13-15-48               Go  51
706   mattermost__mattermost-mobile__2020-06-13_12-0...       JavaScript  50
844            number5__cloud-init__2020-06-12_08-19-08           Python  47
1367                 videolan__vlc__2020-06-11_13-16-50                C  46
1133                    ruby__spec__2020-06-13_23-54-42             Ruby  46
870              openstack__ironic__2020-06-11_01-59-05           Python  45
351   gitextensions__gitextensions__2020-06-13_21-41-09               C#  44
556    JGRennison__OpenTTD-patches__2020-06-10_11-29-22              C++  43
1177    sebastianbergmann__phpunit__2020-06-14_03-38-39              PHP  41
788             Netflix__conductor__2020-06-11_06-17-51             Java  40
1305         Talend__tdi-studio-se__2020-06-13_01-14-06             Java  39
1286               swaywm__wlroots__2020-06-11_20-10-09                C  39
249                  emberjs__data__2020-06-13_20-24-18       JavaScript  36
611          KhronosGroup__glslang__2020-06-13_10-26-07              C++  36
785           nest__nest-simulator__2020-06-13_09-52-37              C++  33
308               freeipa__freeipa__2020-06-11_01-29-37           Python  33
430   GoogleCloudPlatform__nodejs-docs-samples__2020...       JavaScript  33

In [35]:
# Filter projects with team size 16-30
df_sub.loc[(df_sub["TS"] >= 16) & (df_sub["TS"] < 31)]

                                           project_name primary_language  TS
317   functional-streams-for-scala__fs2__2020-06-11_...            Scala  30
237     ElementsProject__lightning__2020-06-11_06-15-59                C  28
1283                  swaggo__swag__2020-06-13_23-31-10               Go  28
626   kiegroup__droolsjbpm-integration__2020-06-13_2...             Java  27
1388                    wix__detox__2020-06-11_07-08-50       JavaScript  26
142    cloudfoundry__cf-deployment__2020-06-13_23-31-34               Go  26
959                   Pyomo__pyomo__2020-06-12_19-25-48           Python  25
202                 diyhue__diyHue__2020-06-13_06-34-31       JavaScript  25
94              aws__aws-lambda-go__2020-06-13_10-42-59               Go  25
1229         SparkDevNetwork__Rock__2020-06-10_14-24-56               C#  24
144     codeigniter4__translations__2020-06-13_17-36-31              PHP  24
1213          sofa-framework__sofa__2020-06-13_15-35-15              C++  23
935   projectceladon__hardware-intel-kernelflinger__...                C  23
287    FasterXML__jackson-databind__2020-06-13_09-34-04             Java  23
723   mongodb__node-mongodb-native__2020-06-13_12-24-56       JavaScript  23
1266   spryker-shop__checkout-page__2020-06-13_01-13-37              PHP  22
124     camicroscope__caMicroscope__2020-06-12_23-42-03       JavaScript  22
1179                  sharkdp__bat__2020-06-13_17-39-48             Rust  20
16              ampproject__amp-wp__2020-06-11_06-11-44              PHP  20
1091              randombit__botan__2020-06-11_01-56-01              C++  20
436   graphql-dotnet__graphql-dotnet__2020-06-14_08-...               C#  19
1310          TeamNewPipe__NewPipe__2020-06-14_03-52-48             Java  18
523         infinispan__infinispan__2020-06-13_00-04-56             Java  16
653         lonnieezell__myth-auth__2020-06-11_01-54-53              PHP  16
1342     Vector35__binaryninja-api__2020-06-11_20-06-50           Python  16

In [36]:
# Filter projects with team size 16-30
df_sub.loc[(df_sub["TS"] >= 9) & (df_sub["TS"] < 16)]

                                           project_name primary_language  TS
777   mulesoft__mule-integration-tests__2020-06-13_2...             Java  15
1064    rabbitmq__rabbitmq-website__2020-06-13_10-06-34       JavaScript  15
579                  KDE__discover__2020-06-14_05-00-18              C++  15
11       alphagov__pay-selfservice__2020-06-10_14-19-45       JavaScript  15
1288   SwitchbladeBot__switchblade__2020-06-11_13-13-19       JavaScript  14
6                   airbnb__enzyme__2020-06-11_01-31-34       JavaScript  14
604             kevinpapst__kimai2__2020-06-14_08-00-24              PHP  14
921              pocoproject__poco__2020-06-13_12-06-23                C  14
1196      sigmavirus24__github3.py__2020-06-13_12-06-02           Python  13
1148         scalacenter__scalafix__2020-06-10_11-29-24            Scala  12
1295  syberia-project__platform_packages_apps_Docume...             Java  12
702   ManageIQ__manageiq-providers-openstack__2020-0...             Ruby  12
1118    rubberduck-vba__Rubberduck__2020-06-11_07-00-07               C#  12
228                  eclipse__birt__2020-06-11_00-34-50             Java  11
559              jsmarcus__Iconize__2020-06-13_21-39-50               C#  11
231   EdgeApp__edge-currency-accountbased__2020-06-1...       JavaScript  11
818          nntaoli-project__GoEx__2020-06-13_15-34-14               Go  11
875         openstack__neutron-lib__2020-06-13_21-40-39           Python  11
103      Azure__azure-sdk-for-node__2020-06-13_10-23-37       JavaScript  11
1218     SoftwareHeritage__swh-web__2020-06-14_03-37-31           Python  10
402                    go-kit__kit__2020-06-14_00-16-47               Go  10
567   jupyterhub__zero-to-jupyterhub-k8s__2020-06-14...           Python  10
563           juju__python-libjuju__2020-06-14_04-38-42           Python  10
532        it-novum__openITCOCKPIT__2020-06-10_13-15-39              PHP  10
852        OpenCHS__openchs-server__2020-06-13_10-22-26             Java   9
453   GTNewHorizons__NewHorizonsCoreMod__2020-06-12_...             Java   9

In [37]:
# Filter projects with team size 5-8
df_sub.loc[(df_sub["TS"] >= 5) & (df_sub["TS"] < 9)]

                                           project_name primary_language  TS
594              KDE__libksysguard__2020-06-14_03-38-20              C++   8
674               lxqt__lxqt-panel__2020-06-12_08-20-48              C++   8
943          puppetlabs__packaging__2020-06-13_20-17-47             Ruby   8
1279              strasdat__Sophus__2020-06-11_13-13-04              C++   8
813            nextcloud__calendar__2020-06-14_00-06-03       JavaScript   8
179     darktable-org__lua-scripts__2020-06-11_00-34-28              Lua   8
501     hyperledger__fabric-sdk-go__2020-06-12_19-25-13               Go   8
886   oroinc__orocommerce-application-de__2020-06-13...              PHP   7
1112                riboseinc__rnp__2020-06-13_21-39-18              C++   7
808                 netxms__netxms__2020-06-11_20-06-02             Java   7
1384  wikimedia__mediawiki-extensions-TemplateStyles...              PHP   7
524   infobloxopen__atlas-app-toolkit__2020-06-13_09...               Go   7
711       mdn__browser-compat-data__2020-06-13_00-10-12       JavaScript   7
163   danielcaldas__react-d3-graph__2020-06-12_04-27-22       JavaScript   7
1377            VOLTTRON__volttron__2020-06-13_15-34-49           Python   7
1421        xfce-mirror__xfdesktop__2020-06-13_00-05-56                C   6
130                chef__cookstyle__2020-06-13_15-34-11             Ruby   6
111   blinkmobile__oneblink-sdk-js__2020-06-13_10-39-33       JavaScript   6
527   isomorphic-git__isomorphic-git__2020-06-13_23-...       JavaScript   6
485        Homebrew__homebrew-cask__2020-06-13_00-14-26             Ruby   5
137            cloudbase__coriolis__2020-06-13_09-28-52           Python   5
447   gstreamer-java__gst1-java-core__2020-06-11_06-...             Java   5
260                   exense__step__2020-06-10_11-25-39             Java   5
54        apache__guacamole-server__2020-06-13_23-51-31                C   5
1424               zclconf__go-cty__2020-06-13_23-30-00               Go   5
507       i18next__i18next-scanner__2020-06-13_12-05-54       JavaScript   5
854        openid__AppAuth-Android__2020-06-13_12-23-59             Java   5
683                  m-labs__migen__2020-06-14_00-16-35           Python   5
239   elgatito__script.elementum.burst__2020-06-14_0...           Python   5
740           mozilla__readability__2020-06-13_05-26-51       JavaScript   5
145     comicrelief__giftaid-react__2020-06-12_04-26-38       JavaScript   5

In [38]:
# Filter projects with team size 2-4
df_sub.loc[(df_sub["TS"] >= 2) & (df_sub["TS"] < 5)]

                                           project_name primary_language  TS
1018         python-caldav__caldav__2020-06-13_05-26-42           Python   4
191        DBCDK__opencat-business__2020-06-13_12-04-37       JavaScript   4
154          CopterExpress__clever__2020-06-13_00-30-49              C++   4
267         fabioz__PyDev.Debugger__2020-06-10_11-22-31           Python   4
196             desihub__desimodel__2020-06-14_00-05-53           Python   4
126           carbonfive__socrates__2020-06-10_13-14-53             Ruby   4
458                 guanzhi__GmSSL__2020-06-11_06-10-35                C   4
734                mozilla__balrog__2020-06-13_10-40-32           Python   4
1270                 stardot__b-em__2020-06-13_23-29-43                C   3
1399    wp-media__rocket-lazy-load__2020-06-11_06-59-15              PHP   3
1422          xiaofengli__codebank__2020-06-14_04-38-01              NaN   3
1249               spotify__folsom__2020-06-13_23-51-20             Java   3
1401  xfce-mirror__xfce4-timer-plugin__2020-06-13_00...                C   3
1426     zs6buj__MavlinkToPassthru__2020-06-13_00-21-03                C   3
907        plone__buildout.coredev__2020-06-14_08-01-34           Python   3
468              hjespers__teslams__2020-06-14_03-37-24       JavaScript   3
1336                   VcDevel__Vc__2020-06-13_11-59-17              C++   3
160      czl0325__ZLCollectionView__2020-06-11_06-08-51      Objective-C   3
1187  ShieldBattery__shieldbattery__2020-06-12_23-41-08       JavaScript   3
199             devsisters__eclair__2020-06-13_12-23-53             Ruby   3
431   gothinkster__flask-realworld-example-app__2020...           Python   3
650         lastaflute__lastaflute__2020-06-13_12-23-35             Java   3
1097           ReactiveX__RxJavaFX__2020-06-11_00-34-15             Java   3
1400  xfce-mirror__thunar-archive-plugin__2020-06-13...                C   2
1320  timw4mail__HummingBirdAnimeClient__2020-06-14_...              PHP   2
1108  RedHatOfficial__miq-Utilities__2020-06-11_01-5...             Ruby   2
1093  Ray-Tracing-Systems__HydraCore__2020-06-12_19-...              C++   2
596    Kekcoin-Core__memechain-api__2020-06-13_17-35-36           Python   2
1280  Strech__sidekiq-prometheus-exporter__2020-06-1...             Ruby   2
1321           TrustWallet__tokens__2020-06-11_01-43-34       JavaScript   2
1380              weld__weld-junit__2020-06-12_04-26-30             Java   2
464   Hipo__university-domains-list__2020-06-13_10-4...           Python   2
1329             txteam__tx-parent__2020-06-13_09-29-31             Java   2
109      baukh789__GridManager-Vue__2020-06-10_11-21-50       JavaScript   2
1371          ViewTouch__viewtouch__2020-06-12_04-22-02              C++   2
81     arduino-libraries__Ethernet__2020-06-13_10-22-19              C++   2
899            pdxwebdev__yadacoin__2020-06-14_06-02-30       JavaScript   2
117   braintree__android-card-form__2020-06-13_17-36-19             Java   2
132               chinedufn__percy__2020-06-11_01-55-48             Rust   2
151      contentful__contentful.js__2020-06-13_23-30-16       JavaScript   2
173   danmarsden__moodle-plagiarism_urkund__2020-06-...              PHP   2
210                dmfs__opentasks__2020-06-13_00-30-23             Java   2
510         ihmcrobotics__joctomap__2020-06-13_21-39-04             Java   2
654          loopmediagroup__gally__2020-06-11_06-09-12       JavaScript   2
708           mautic__mautic-typo3__2020-06-12_19-22-53              PHP   2
779       mysql-net__AdoNetApiTest__2020-06-11_00-34-01               C#   2
848     nuxeo__nuxeo-python-client__2020-06-11_01-55-21           Python   2
1            7compass__sentimental__2020-06-13_10-18-00             Ruby   2